<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0 items</name>
   <tag></tag>
   <elementGuidId>729e0d25-b63e-4ff8-b7c5-f0402256c830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.cart-items-info</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'cart-items-info']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='headerDesktopView']/div[3]/div/ul/li[3]/div/div/a/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cart-items-info</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0 items</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headerDesktopView&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;header-utility-inner&quot;]/ul[@class=&quot;utility-links&quot;]/li[@class=&quot;yCmsContentSlot mini-cart-wp componentContainer header-cart-menu menu-shown&quot;]/div[@class=&quot;yCmsComponent&quot;]/div[@class=&quot;dropdown&quot;]/a[@class=&quot;mobile-icon js-mini-cart-link&quot;]/span[@class=&quot;hidden-xs hidden-sm&quot;]/span[@class=&quot;js-populated-cart-message&quot;]/span[@class=&quot;cart-items-info&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='headerDesktopView']/div[3]/div/ul/li[3]/div/div/a/span/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Account'])[2]/following::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(0)'])[1]/preceding::span[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oh no! Your shopping cart is still empty.'])[1]/preceding::span[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='items']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
   </webElementXpaths>
</WebElementEntity>
