<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Sign In  Create Account_loginHeaderIframe1</name>
   <tag></tag>
   <elementGuidId>f0cb9d69-5289-439b-9d09-e69e9dd08e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#loginHeaderIframe1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='loginHeaderIframe1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loginHeaderIframe1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a1848c4e-0499-4a9c-91da-25327a81e72e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginHeaderIframe1</value>
      <webElementGuid>8dbdb73b-d62c-4252-a088-93ad99fe3a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginHeaderIframe</value>
      <webElementGuid>c23164bb-bbf2-4ad4-8ed8-144481742aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Log in iframe</value>
      <webElementGuid>c54815f1-33dc-48c3-8175-8d760f8e2a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://uat01.sso.bncollege.com/bes-oid/oauth/authorize?response_type=code&amp;scope=openid%20profile&amp;display=popup&amp;redirect_uri=https%3A%2F%2Fmichigan.uat1.helixbeta.com%2Fopid%2Fcallback&amp;state=Dl6kHTGg%2F5%2FaEFWanpQSfg07EcLTW+%2FLyp3uXWo%3D&amp;client_id=michigan-ecom</value>
      <webElementGuid>74291562-5182-4321-8cba-102514e6084c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginHeaderIframe1&quot;)</value>
      <webElementGuid>b9ce730a-b2cb-40ae-afcc-7d2ee4b8bc02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='loginHeaderIframe1']</value>
      <webElementGuid>a3f89149-1dc5-416f-89c2-583b2931d9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='headerDesktopView']/div[5]/div/ul/li/div/div/div/div/div/div/iframe</value>
      <webElementGuid>fc830bbf-8cd2-4894-946c-109fdb66aa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/iframe</value>
      <webElementGuid>ead66fe5-64bd-42ae-a922-3e83fabcc76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'loginHeaderIframe1' and @title = 'Log in iframe' and @src = 'https://uat01.sso.bncollege.com/bes-oid/oauth/authorize?response_type=code&amp;scope=openid%20profile&amp;display=popup&amp;redirect_uri=https%3A%2F%2Fmichigan.uat1.helixbeta.com%2Fopid%2Fcallback&amp;state=Dl6kHTGg%2F5%2FaEFWanpQSfg07EcLTW+%2FLyp3uXWo%3D&amp;client_id=michigan-ecom']</value>
      <webElementGuid>6031e8ce-d1ef-420a-95d9-f56fab4968ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
