<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Notes (0)_btn btn-sm button-secondary</name>
   <tag></tag>
   <elementGuidId>ec613e26-6db6-4162-af13-b9cdda2ea3f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'Done' or . = 'Done')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#single-spa-application\:homeContainer > isf-orders-extn-root > isf-order-summary-page > div > div.d-flex.flex-wrap.w-100.align-items-center.bg-white.isf-border-bottom.header-panel.h-auto.m-0 > div.d-none.d-md-flex.float-end.actions.align-items-center > button:nth-child(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Done&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc840b40-8865-487b-835c-b923f18d07b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09395432-5331-4790-bde6-576df0468022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm button-secondary</value>
      <webElementGuid>5c4e89b6-732e-409e-85b2-870e7c43fa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tid</name>
      <type>Main</type>
      <value>orderSummaryPageDoneButton</value>
      <webElementGuid>69057504-d75e-4f41-ad4a-8339dcd5a380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>3fbed8f7-b0c9-43a9-a3cb-96b3829ad81a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:homeContainer&quot;)/isf-orders-extn-root[1]/isf-order-summary-page[1]/div[@class=&quot;isf-order-summary-page position-relative&quot;]/div[@class=&quot;d-flex flex-wrap w-100 align-items-center bg-white isf-border-bottom header-panel h-auto m-0&quot;]/div[@class=&quot;d-none d-md-flex float-end actions align-items-center&quot;]/button[@class=&quot;btn btn-sm button-secondary&quot;]</value>
      <webElementGuid>9e8d4ca1-710e-47a3-9977-b015db7bb7c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>62c322be-5301-4986-808e-24f70478da47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:homeContainer']/isf-orders-extn-root/isf-order-summary-page/div/div/div[4]/button[3]</value>
      <webElementGuid>ce51f35a-e2ca-4488-afee-a3bb258d726e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notes (0)'])[1]/following::button[1]</value>
      <webElementGuid>a0c17e7e-83e3-4c08-8a3a-91995ae73960</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::button[2]</value>
      <webElementGuid>d577c8ed-a03d-4c69-944b-b666ee4e4248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order status'])[1]/preceding::button[2]</value>
      <webElementGuid>0f3ac4e5-9d47-4244-9b0c-0ef117ce75e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Digital Fulfilled'])[1]/preceding::button[2]</value>
      <webElementGuid>ab666a90-b7d0-4fd7-ba41-71142aa8cabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>ca21c4e5-73be-4067-9674-b0c836273263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>5bcbb3af-13fb-4689-a12e-7d601bfc35d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>4cbb5bb1-87e3-406f-b736-abf663ba436e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
