<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tracking</name>
   <tag></tag>
   <elementGuidId>4a40478b-3d23-4b64-b94a-3ae5a8f3a6e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='inputField'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col.p-0.bg-white > isf-packages > div.row.bg-white.m-0 > div.col-12.p-0 > div.row.m-0.isf-padding-x-20.isf-padding-bottom-10.border-bottom > div.col-md-8.col-6.p-0 > div:nth-of-type(4) > #inputField</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>isf-packages >> internal:has-text=&quot;Pack allAddPackage 1 # 100021707 1 productTracking #Pounds Please enter weight g&quot;i >> #inputField</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30d0a733-573f-4c5d-bec3-96401bdea371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f4747f0-830f-47f6-8f29-940f7f70172d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputField</value>
      <webElementGuid>ffcd0022-27a0-46a0-a3ce-28c38717e3a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>isf-margin-right-10 ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>dfa51872-608b-48d7-8511-2686bf5d52d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;single-spa-application:homeContainer&quot;)/isf-pack-order-extn-root[1]/isf-pack-order-page[1]/form[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/div[@class=&quot;isf-page-content row pack-page-font-size&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row d-none d-md-flex&quot;]/div[@class=&quot;col-md-8 ps-3&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col p-0 bg-white&quot;]/isf-packages[1]/div[@class=&quot;row bg-white m-0&quot;]/div[@class=&quot;col-12 p-0&quot;]/div[@class=&quot;row m-0 isf-padding-x-20 isf-padding-bottom-10 border-bottom&quot;]/div[@class=&quot;col-md-8 col-6 p-0&quot;]/div[4]/input[@id=&quot;inputField&quot;]</value>
      <webElementGuid>cd742d6c-409a-4bda-a3c2-bcfbdf72177f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='inputField'])[2]</value>
      <webElementGuid>aff759d8-89e6-44ce-8a44-2da88a8ca442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='single-spa-application:homeContainer']/isf-pack-order-extn-root/isf-pack-order-page/form/div/div[3]/div[2]/div[2]/div/div/isf-packages/div/div[3]/div/div/div[4]/input</value>
      <webElementGuid>6790f5ef-a294-439b-934d-9e7ff9b37876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/isf-packages/div/div[3]/div/div/div[4]/input</value>
      <webElementGuid>f782ac2a-364c-40fd-9bbe-05bfe555ad90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputField']</value>
      <webElementGuid>3f2712a2-bc7c-4ab9-82ea-e7991803c257</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
