<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tracking No_weight</name>
   <tag></tag>
   <elementGuidId>c8c1d37e-078d-4a58-99ae-903530702771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='weight']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;weight&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>0.0001</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-focus</name>
      <type>Main</type>
      <value>uiOnWeightFieldFocus(this,ui.currentContainerDetails)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>ui.currentContainerDetails.ActualWeight</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isc-datatype</name>
      <type>Main</type>
      <value>{
	                'customValidator': uiValidateWeight, 'datatype':'ActualWeight',
	                'useOnlyCustomValidator':false}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>weightForm.weight.$valid ? uiShowWeightUpdateButton(this,ui.currentContainerDetails) : uiHideWeightUpdateButton(ui.currentContainerDetails)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isc-enter</name>
      <type>Main</type>
      <value>weightForm.weight.$valid ? uiValidateWeightAndUpdate(this,ui.currentContainerDetails) : null</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control weight-box ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-step ng-valid-isc-datatype-validator ng-valid-isc-custom-validator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContentHolder&quot;)/div[@class=&quot;screen-container&quot;]/div[@class=&quot;wizard-template&quot;]/div[@class=&quot;wizard-page&quot;]/div[@class=&quot;container-pack ng-dirty ng-valid-parse ng-valid-isc-datatype-validator ng-valid-step ng-valid ng-valid-isc-custom-validator&quot;]/div[@class=&quot;screen-holder has-header-secondary whole-screen&quot;]/div[@class=&quot;container-pack-details container-pack-details-success&quot;]/div[@class=&quot;pack-details&quot;]/div[@class=&quot;container-list-main&quot;]/div[@class=&quot;container-screen&quot;]/div[@class=&quot;current-container-details&quot;]/div[@class=&quot;package-details-header&quot;]/div[@class=&quot;form-view package-weight&quot;]/div[@class=&quot;ng-pristine ng-valid ng-valid-step ng-valid-isc-datatype-validator ng-valid-isc-custom-validator&quot;]/input[@class=&quot;form-control weight-box ng-pristine ng-untouched ng-valid ng-not-empty ng-valid-step ng-valid-isc-datatype-validator ng-valid-isc-custom-validator&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='weight']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContentHolder']/div[2]/div/div[2]/div/div/div[3]/div/div[2]/div/div[3]/div/div[2]/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
   </webElementXpaths>
</WebElementEntity>
