<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_WINTER-1 2025</name>
   <tag></tag>
   <elementGuidId>adee14f3-2fdd-4fcf-9012-eb959b188c66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[text() = 'WINTER-1 2025']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select2-7q34-result-ndbe-680_1_25_B</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;WINTER-1 2025&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a310a0ee-29bb-40d4-a82c-0a68cdcee2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>ade134c7-7386-467d-b85b-ad66ca5d7722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-7q34-result-ndbe-680_1_25_B</value>
      <webElementGuid>f32b8254-019e-4bc3-9162-73af046477fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>18ecb529-7146-4667-bc06-fc43fd738e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>79a72e28-8408-46cb-a973-75d09b1b02de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-7q34-result-ndbe-680_1_25_B</value>
      <webElementGuid>0bfda72b-fabe-4e5f-a9ae-92222e1e4df2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WINTER-1 2025</value>
      <webElementGuid>434c907d-3649-4bf5-8b43-b3b6c4261944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-7q34-result-ndbe-680_1_25_B&quot;)</value>
      <webElementGuid>74fb98af-f0f5-4db0-965e-b35990dde3e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-7q34-result-ndbe-680_1_25_B']</value>
      <webElementGuid>7be9e47a-fcbe-4fe2-86e5-77cd620f75a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-7q34-results']/li[2]</value>
      <webElementGuid>984d5a8a-0c2a-4d5c-9306-4a25de21e45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[7]/following::li[2]</value>
      <webElementGuid>90a76721-14dd-4067-bfc2-4893a441008d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term'])[4]/following::li[2]</value>
      <webElementGuid>eb5c0f34-3ad7-46da-be41-609dca428450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Late Fall 2025'])[2]/preceding::li[1]</value>
      <webElementGuid>dc0762ed-5401-4449-816a-f3bcef87349b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spring 2025'])[2]/preceding::li[2]</value>
      <webElementGuid>f79afbbf-67c7-4b58-bdaf-7a66db8e48e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>543c5abd-f9f6-42a2-9fbe-124368c73924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-7q34-result-ndbe-680_1_25_B' and (text() = 'WINTER-1 2025' or . = 'WINTER-1 2025')]</value>
      <webElementGuid>eb080283-00c1-4ccf-9ee0-6d7dd0255cdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
