<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>98dd79ec-61cf-4feb-8167-45e25534283e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mainContent']/div/div/div/div/div[4]/div[2]/form/div/div[2]/div[2]/div/div/div/span/span/span</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mainContent&quot;)/div[@class=&quot;yCmsContentSlot course-finder-center-content-component&quot;]/div[@class=&quot;yCmsComponent course-finder-center-content-component&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;bned-container-cf&quot;]/div[@class=&quot;bned-cf-container&quot;]/div[@class=&quot;bned-course-finder-form-wrapper&quot;]/form[@class=&quot;js-course-finder-form&quot;]/div[@class=&quot;bned-campus-form js-bned-campus-form js-bned-campus-not-previous-search js-course-finder-element&quot;]/div[@class=&quot;bned-rows-block js-bned-rows-block js-accessibility-table&quot;]/div[@class=&quot;bned-register-section bned-course-row-wp js-course-row js-bned-course-not-previous-search js-course-finder-element&quot;]/div[@class=&quot;bned-select-item js-bned-select-item terms&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;control&quot;]/span[@class=&quot;select2 select2-container select2-container--default select2-container--above&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;][count(. | //span[@class = 'select2-selection select2-selection--single' and @role = 'combobox' and @aria-haspopup = 'true' and @aria-expanded = 'false' and @tabindex = '0' and @aria-disabled = 'false' and @aria-label = 'Select
                    Term' and (text() = 'Select' or . = 'Select')]) = count(//span[@class = 'select2-selection select2-selection--single' and @role = 'combobox' and @aria-haspopup = 'true' and @aria-expanded = 'false' and @tabindex = '0' and @aria-disabled = 'false' and @aria-label = 'Select
                    Term' and (text() = 'Select' or . = 'Select')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.control > span.select2.select2-container.select2-container--default > span.selection > span.select2-selection.select2-selection--single</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Select\n                    Term&quot;i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b1c0c1bf-25a3-4679-9bd6-75d7eb074406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single</value>
      <webElementGuid>1e7b15c7-a424-4445-9c8f-5fd129415641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>b432baeb-1eec-4227-9339-23be20040006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd0c412f-6958-4746-b803-da376da0446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>025b9451-a76b-4928-bbea-0bb2d0741f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68908712-259d-4d4c-8ddd-a0e9e7c79e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eda2217e-7016-44e4-9c9e-98a98ae6cdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select
                    Term</value>
      <webElementGuid>23eeb7bf-391d-4908-8169-5107197d93d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>6462f928-a10e-42d3-acd7-6656d382c3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;yCmsContentSlot course-finder-center-content-component&quot;]/div[@class=&quot;yCmsComponent course-finder-center-content-component&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;bned-container-cf&quot;]/div[@class=&quot;bned-cf-container&quot;]/div[@class=&quot;bned-course-finder-form-wrapper&quot;]/form[@class=&quot;js-course-finder-form&quot;]/div[@class=&quot;bned-campus-form js-bned-campus-form js-bned-campus-not-previous-search js-course-finder-element&quot;]/div[@class=&quot;bned-rows-block js-bned-rows-block js-accessibility-table&quot;]/div[@class=&quot;bned-register-section bned-course-row-wp js-course-row js-bned-course-not-previous-search js-course-finder-element&quot;]/div[@class=&quot;bned-select-item js-bned-select-item terms&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;control&quot;]/span[@class=&quot;select2 select2-container select2-container--default&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]</value>
      <webElementGuid>94ec52c3-e9e8-4c6e-bb2c-dd2ee17f4e07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div/div/div/div[4]/div[2]/form/div/div[2]/div[2]/div/div/div/span/span/span</value>
      <webElementGuid>92c858cf-f880-41c1-8fb0-5c9e1844b352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term'])[4]/following::span[3]</value>
      <webElementGuid>8f55e55b-7b00-4103-ba93-7774b8742500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Information'])[2]/following::span[3]</value>
      <webElementGuid>c89d1433-817b-431f-9dab-e77321c6173d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Department'])[4]/preceding::span[4]</value>
      <webElementGuid>8d829a46-af9d-4f3d-9603-a175018ec0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/span/span/span</value>
      <webElementGuid>6cb90961-86df-46a5-825d-80f4bfcca14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>1d357570-f52b-413c-a5ba-fb5247f353a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
