<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Spring 2025</name>
   <tag></tag>
   <elementGuidId>5ddcfcb3-a3a0-4070-b6f6-d9298a811100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-7q34-result-ndbe-680_1_25_B</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[text() = 'Spring 2025']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=option[name=&quot;WINTER-1 2025&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>03c7903f-33bc-4d39-ba32-0515c97ca821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>6c8b60dd-2ef5-4c52-bfd4-d1b234f49e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-7q34-result-ndbe-680_1_25_B</value>
      <webElementGuid>9975e0e5-ac2d-4d92-99b4-7f0b174de33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>d7fbf5ef-d479-406d-91ce-e2b844a5bed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83d5a95d-9eb0-4d68-a332-0a3c8d643a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-7q34-result-ndbe-680_1_25_B</value>
      <webElementGuid>15b04ace-defc-4104-bffb-bcf710de55db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WINTER-1 2025</value>
      <webElementGuid>e16c89ce-2851-4f24-9ad1-cc25886d78e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-7q34-result-ndbe-680_1_25_B&quot;)</value>
      <webElementGuid>c9122f38-8069-416b-96bd-7c8b9a4f3cdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-7q34-result-ndbe-680_1_25_B']</value>
      <webElementGuid>73858bdf-3fb6-484a-9f05-0656a2afe9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-7q34-results']/li[2]</value>
      <webElementGuid>9483a158-a28e-4b52-855f-680a9055bc38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[7]/following::li[2]</value>
      <webElementGuid>03ebe123-522b-4aad-9669-954b821d13ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Term'])[4]/following::li[2]</value>
      <webElementGuid>e8eb9736-ce50-4dcd-abc8-f7fd6cca898c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Late Fall 2025'])[2]/preceding::li[1]</value>
      <webElementGuid>d25bd1dc-85e9-4128-8003-2a983ea9f470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spring 2025'])[2]/preceding::li[2]</value>
      <webElementGuid>d927b447-2319-40f1-bb9d-a11dad33be4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/ul/li[2]</value>
      <webElementGuid>57137668-8fa9-4069-b16c-2bfa77dea4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-7q34-result-ndbe-680_1_25_B' and (text() = 'WINTER-1 2025' or . = 'WINTER-1 2025')]</value>
      <webElementGuid>7756d448-6752-4519-b921-ebd76a0cb99f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
