<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rental_search_box</name>
   <tag></tag>
   <elementGuidId>606bc5ef-9ba6-4b9c-aba3-7d67ccbedb6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='pack_shipmentOrderBarcodeScanner'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isc-i18n</name>
      <type>Main</type>
      <value>[placeholder]EXTN_rentalOrders.TITLE_ScanOrEnterOrder[}{][aria-label]EXTN_rentalOrders.TITLE_ScanOrEnterOrder[}{][title]EXTN_rentalOrders.TITLE_ScanOrEnterOrder</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>model.scanInput.value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isc-enter</name>
      <type>Main</type>
      <value>uiScanBarCodeData('SCAN',$event)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isc-barcode-scanner</name>
      <type>Main</type>
      <value>DEFAULT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pack_shipmentOrderBarcodeScanner</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Scan or enter order #</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Scan or enter order #</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Scan or enter order #</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContentHolder&quot;)/div[@class=&quot;screen-container&quot;]/div[@class=&quot;home-page persona-home-page screen-holder&quot;]/div[@class=&quot;home-page-carousel&quot;]/div[@class=&quot;portlet-set carousel&quot;]/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;item active&quot;]/div[@class=&quot;text-center&quot;]/div[@class=&quot;portlet-content portlet-tile-3&quot;]/div[1]/div[@class=&quot;moretasks-transition-holder&quot;]/div[@class=&quot;moretasks-expanded-content-holder moretasks-transition-content show-full-portlet&quot;]/div[2]/div[@class=&quot;portlet-holder rental-order-theme portlet-transition&quot;]/div[@class=&quot;portlet-transition-holder chart-portlet-transition-holder&quot;]/div[@class=&quot;chart-style-holder chart-style-content transition-content screen-initial&quot;]/div[2]/isc-shipment-order-barcode-scanner[1]/div[@class=&quot;input-group input-icon&quot;]/input[@id=&quot;pack_shipmentOrderBarcodeScanner&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='pack_shipmentOrderBarcodeScanner'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContentHolder']/div[2]/div/div[2]/div[2]/div/div/div/div[3]/div/div/div[2]/div[2]/div/div/div/div[2]/isc-shipment-order-barcode-scanner/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/isc-shipment-order-barcode-scanner/div/input</value>
   </webElementXpaths>
</WebElementEntity>
