<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_I agree with the BN Rental Terms and Conditions_control__indicator</name>
   <tag></tag>
   <elementGuidId>c96b91ac-8a26-40aa-9bab-9ac3d745f46a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='bnedConsentForm']/div/div[2]/div[3]/div/label/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.control__indicator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control__indicator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bnedConsentForm&quot;)/div[@class=&quot;bned-consents-wp&quot;]/div[@class=&quot;bned-consent&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;checkbox&quot;]/label[@class=&quot;control-label element-focusable add-address-left-label&quot;]/div[@class=&quot;control__indicator&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bnedConsentForm']/div/div[2]/div[3]/div/label/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
   </webElementXpaths>
</WebElementEntity>
